[[setup]]
= Установка

[partintro]
--
Данный раздел включает информацию о установке, настройке и запуске *elasticsearch*. Если вы ещё этого не сделали
http://www.elastic.co/downloads[скачайте] продукт и затем прочтите <<setup-installation,документацию по установке>>

NOTE: Elasticsearch может быть также установлен из наших репозиториев, используя `apt` или `yum`.
См. <<setup-repositories>>.

[[supported-platforms]]
[float]
== Поддерживаемые платформы

Матрица официально поддерживыемых операционных систем и JVM доступны здесь:
link:/support/matrix[Support Matrix].  Elasticsearch тестируется на данном
перечне платформ, но возможно, что он также будет работать и на других платформах.

[[setup-installation]]
[float]
== Установка

После link:/downloads/elasticsearch[скачивания] и распаковки последней версии,
можно запустить *elasticsearch* с помощью команды:

[source,sh]
--------------------------------------------------
$ bin/elasticsearch
--------------------------------------------------

В системах *nix, команда запустит процесс как программу.

[[setup-installation-daemon]]
[float]
=== Запуск в режиме демона

Чтобы запустить Elasticsearch в фоновом режиме, добавьте опцию `-d`:

[source,sh]
--------------------------------------------------
$ bin/elasticsearch -d
--------------------------------------------------

[[setup-installation-pid]]
[float]
=== PID

Процесс Elasticsearch может при запуске записать свой PID (идентификатор процесса) 
в указанный файл, что в последствии делает лёгким завершение процесса:

[source,sh]
--------------------------------------------------
$ bin/elasticsearch -d -p pid <1>
$ kill `cat pid` <2>
--------------------------------------------------
<1> PID записывается в файл с именем `pid`.
<2> Команда `kill` отправляет сигнал `TERM` для процесса, PID которого сохранён в файле `pid`.

NOTE: скрипты запуска, предоставляемые для <<setup-service,Linux>> и <<setup-service-win,Windows>>
позаботятся о запуске и остановке процесса Elasticsearch для вас.

.*NIX
*************************************************************************
При использовании shell-скрипта для запуска `elasticsearch` существуют
дополнительные возможности. Во-первых, как было рассказано ранее,
возможность лёгкго запуска процесса в режим программы или в фоновом режиме.

Другая возможность состоит в указании данному скрипту напрямую опции
`-D` или опций в виде конфигурационных параметров в длинном стиле.
Когда задаются эти опции, они перекрывают всё, что установлено в переменных
окружения `JAVA_OPTS` или `ES_JAVA_OPTS`. Например:

[source,sh]
--------------------------------------------------
$ bin/elasticsearch -Des.index.refresh_interval=5s --node.name=my-node
--------------------------------------------------
*************************************************************************

[float]
[[jvm-version]]
== Версия Java (JVM)

Elasticsearch написан на языке Java и требует для запуска как минимум
http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java 8].
Поддерживаются только реализации Java от Oracle и OpenJDK. И узлы кластера
и клиенты Elasticsearch должны использовать одинаковые версии JVM.

Мы рекомендуем установить *Java 8 update 20 или более позднюю версию* или
*Java 7 update 55 или более позднюю версию*. Предыдущие версии Java 7 содержат
известные ошибки, которые могут привести к повреждению индекса и потере данных.
Elasticsearch не будет запускаться, если будет использована одна из таких версий.

Версия Java, которая будет использована для запуска, зависит от переменной
окружения `JAVA_HOME`.

--

include::setup/configuration.asciidoc[]

include::setup/as-a-service.asciidoc[]

include::setup/as-a-service-win.asciidoc[]

include::setup/dir-layout.asciidoc[]

include::setup/repositories.asciidoc[]

include::setup/upgrade.asciidoc[]
