[[setup-service]]
== Запуск в режиме службы в Linux

Для запуска elasticsearch как службы в вашей операционной системе, предоставляемые пакеты пытаются сделать запуск и останов elasticsearch как можно более лёгким во время загрузки и при обновлении.

[float]
=== Linux

В настоящее время, процесс сборки пакетов автоматически создаёт пакеты Debian и RPM, которые доступны на странице скачивания. Сам пакет не имеет каких-либо зависимостей, но вы должны убедиться, что у вас установлен JDK. (На самом деле имеется в виду Java JRE с сайта java.com – прим.пер)

Каждый пакет имеет конфигурационный файл, который позволяет вам установить следующие параметры

[horizontal]
`ES_USER`::               Пользователь с правами которого осуществляется запуск, по умолчанию `elasticsearch`
`ES_GROUP`::              Группа с правами которой осуществляется запуск, по умолчанию `elasticsearch`
`ES_HEAP_SIZE`::          Размер кучи для запуска
`ES_HEAP_NEWSIZE`::       Размер новой сгенерированной кучи
`ES_DIRECT_SIZE`::        Максимальный размер памяти с прямым доступом
`MAX_OPEN_FILES`::        Максимальное число открытых файлов, по умолчанию `65535`
`MAX_LOCKED_MEMORY`::     Максимальный размер блокируемой памяти. Установите "ulimited" если вы используете опцию `bootstrap.mlockall` в `elasticsearch.yml`. Вы должны также установить `ES_HEAP_SIZE`.
`MAX_MAP_COUNT`::         Максимальное количество областей карт памяти.  Если вы используете `mmapfs` для хранения индекса, убедитесь, что вы установили достаточно большое значение. Подробности смотрите в https://github.com/torvalds/linux/blob/master/Documentation/sysctl/vm.txt[документации по ядру linux] о `max_map_count`. Данное значение устанавливается через `sysctl` перед запуском elasticsearch. По умолчанию `65535`
`LOG_DIR`::               Каталог для логов, по умолчанию `/var/log/elasticsearch`
`DATA_DIR`::              Каталог с данными, по умолчанию `/var/lib/elasticsearch`
`CONF_DIR`::              Каталог с файлами конфигурации (которые необходимо подключить к `elasticsearch.yml` и `logging.yml`), по умолчанию `/etc/elasticsearch`
`ES_JAVA_OPTS`::          Любые дополнительные опции для Java, которые вы захотите установить. Это может быть полезно, если вам нужно установить свойство `node.name`, но вы не хотите изменять файл конфигурации `elasticsearch.yml`, потому что он распространяется на другие компьютеры через такие системы группового управления как puppet или chef. Пример: `ES_JAVA_OPTS="-Des.node.name=search-01"`
`RESTART_ON_UPGRADE`::    Настраивает перезапуск при обновлении, по умолчанию `false`. Это означает, что вы будете должны перезапустить ваш экземпляр elasticsearch вручную, после установки пакета. Причина состоит в необходимости иметь уверенность, что обновление кластера не вызовет продолжительное перемещение шардов между нодами с высокими сетевым трафиком, что снизит время реакции вашего кластера.
`ES_GC_LOG_FILE` ::       Абсолютный путь к файлу лога для создания файла логгирования сборки мусора, которое выполняет JVM. Обратите внимание, что этот файл лога может быстро расти и поэтому по умолчанию выключен.

[float]
==== Debian/Ubuntu

Пакет для Debian предоставляет всё что нужно, чтобы использовать стандартные инструменты Debian, такие как обновление `update-rc.d`, чтобы задать необходимые уровни запуска для запуска. Скрипт инициализации ожидаемо называется `/etc/init.d/elasticsearch`. Конфигурационный файл размещается в `/etc/default/elasticsearch`.

Пакет для Debian не запускает службу по умолчанию. Причиной является предотвращение случайного присоединения запущенного экземпляра к кластеру до выполнения необходимых настроек. После установки с помощью dpkg -i, чтобы убедиться в том, что elasticsearch запускается при загрузке системы и для самого запуска, вы можете использовать следующие команды:

[source,sh]
--------------------------------------------------
sudo update-rc.d elasticsearch defaults 95 10
sudo /etc/init.d/elasticsearch start
--------------------------------------------------

Пользователям, работающим с Debian 8 или Ubutntu 14 и более поздних версий, могут потребоваться конфигурации `systemd` вместо `update-rc.d`. В этому случае, см. раздел <<using-systemd>>.

[float]
===== Установка Oracle JDK

Обычная рекомендация состоит в запуске elasticsearch с Oracle JDK. Однако Ubuntu и Debian поставляются только с OpenJDK из-за лицензионных ограничений. Вы можете легко установить инсталлятор пакета Oracle JDK. В случае отсутствия команды `add-apt-repository` в Debian GNU/Linux, убедитесь, что у вас по крайней мере Debian версии Wheezy и установлен пакет `python-software-properties`

[source,sh]
--------------------------------------------------
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
java -version
--------------------------------------------------

Последняя команда должна проверить успешность установки Oracle JDK.


[float]
==== Дистрибутивы, основанные на RPM

[float]
===== Использование chkconfig

Некоторые основанные на RPM дистрибутивы, используют `chkconfig`, чтобы включать и выключать службы. Скриптом инициализации является `/etc/init.d/elasticsearch`, а конфигурационным файлом является `/etc/sysconfig/elasticsearch`. Как и для пакета Debian, для пакета RPM после установки elasticsearch по умолчанию автоматически не запускается, вы должны сделать это вручную, с помощью следующих команд:

[source,sh]
--------------------------------------------------
sudo /sbin/chkconfig --add elasticsearch
sudo service elasticsearch start
--------------------------------------------------

[[using-systemd]]
[float]
==== Использование systemd

Такие дистрибутивы как Debian Jessie, Ubuntu 14 и многие производные от SUSE не используют инструмент chkconfig для регистрации служб, а используют вместо этого для запуска и останова служб `systemd` и его команду `/bin/systemctl` (по крайней мере новые версии, в противном случае используйте команду `chkconfig`, описанную выше). Конфигурационным файлом также является `/etc/sysconfig/elasticsearch`, если система основана на RPM и `/etc/default/elasticsearch` если на DPKG. После установки RPM пакета, вы должны изменить конфигурацию `systemd` и затем запустить elasticsearch

[source,sh]
--------------------------------------------------
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable elasticsearch.service
sudo /bin/systemctl start elasticsearch.service
--------------------------------------------------

Также, обратите внимание, что изменение настройки `MAX_MAP_COUNT` в `/etc/sysconfig/elasticsearch` не будет иметь никакого эффекта, вы должны изменить её в файле `/usr/lib/sysctl.d/elasticsearch.conf` чтобы она применилась при запуске.

