[[backup]]
=== Резервное копирование ваших данных!

Всегда выполняйте резервное копирование ваших данных перед выполнением обновления.
Это позволит вам откатится к предыдущему состоянию в случае возникновения каких-либо
проблем при обновлении. Обновления иногда включают обновления библиотек Lucene,
которые Elasticsearch использует для доступа к индексным файлам, и после того как
индексный файл будет обновлён для работы с новой версией Lucene, он может стать
недоступным для версий библиотек Lucene, поставлямых в более ранних выпусках
Elasticsearch.

[WARNING]
.Всегда делайте резервную копию ваших данных перед обновлением
=========================================
Вы не сможете откатится на предыдущую версию если у вас не будет резервной
копии ваших данных.
=========================================

==== Резервное копирование, начиная с версии 1.0 и далее

Для выполнения резервного копирования версий 1.0 и выше, простейшим методом является
использование мгновенных снимков (снапшотов) диска. Полные инструкции для
резервного копирования и восстановления с помощью мгновенных снимков доступны в
документации по
<<modules-snapshots,резервному копированию и восстановлению с помощью мгновенных снимков>>.

==== Резервное копирование версии 0.90.x и более ранних

Чтобы сделать резервную копию запущенной версии 0.90.x:

===== Шаг 1: Выключите сброс индекса на диск

Это предотвратит сброс индексов на диск во время выполнения резервного копирования:

[source,js]
-----------------------------------
PUT /_all/_settings
{
  "index": {
    "translog.disable_flush": "true"
  }
}
-----------------------------------
// AUTOSENSE

===== Шаг 2: Выключите реаллокацию (перемещение шардов по узлам кластера)

Это предотвратит перемещение файлов данных с одного узла кластера на другой
во время резервного копирования:

[source,js]
-----------------------------------
PUT /_cluster/settings
{
  "transient": {
    "cluster.routing.allocation.disable_allocation": "true"
  }
}
-----------------------------------
// AUTOSENSE

===== Шаг 3: Выполните резервное копирование данных

После запрета реаллокации и сброса индексов, инициируйте резервное копирование
каталогов с данными Elasticsearch предпочитаемым вами способом (tar, мгновенные
снимки дисковых массивов (снапшоты), другое ПО резервного копирования).

===== Шаг 4: Включите реаллокацию и сброс индексов на диск

Когда резервное копирование завершится и данные из каталогов больше не нужно
будет читать, реаллокацию и сброс индексов необходимо включить:

[source,js]
-----------------------------------
PUT /_all/_settings
{
  "index": {
    "translog.disable_flush": "false"
  }
}

PUT /_cluster/settings
{
  "transient": {
    "cluster.routing.allocation.disable_allocation": "false"
  }
}
-----------------------------------
// AUTOSENSE
