[[setup-upgrade]]
== Обновление

[IMPORTANT]
===========================================
Перед обновлением Elasticsearch:

* Прочтите документацию про <<breaking-changes,изменения, нарушающие совместимость>>.
* Протестируйте обновления в окружении разработки перед обновлением продуктивного кластера.
* Всегда делайте резервную копию данных перед обновлением. Вы не сможете откатиться на
предыдущую версию, если у вас не будет <<backup,резервной копии>> ваших данных.
===========================================

Обычно Elasticsearch можно обновить, используя накатывающий процесс обновления
и в результате не прерывать работу службы. Данный раздел детально описывает
как выполнить накатывающее обновление и обновление с полным перезапуском
кластера.

Чтобы определить поддерживается ли накатывающее обновление для вашего выпуска, пожалуйста
посмотрите данную таблицу:

[cols="1<m,1<m,3",options="header",]
|=======================================================================
|Обновление с   |Обновление на  |Поддерживаемый тип обновления
|0.90.x         |1.x, 2.x       |<<restart-upgrade,Полный перезапуск кластера>>
|< 0.90.7       |0.90.x         |<<restart-upgrade,Полный перезапуск кластера>>
|>= 0.90.7      |0.90.x         |<<rolling-upgrades,Накатывающее обновление>>
|1.0.0 - 1.3.1  |1.x            |<<rolling-upgrades,Накатывающее обновление>> (если <<recovery,`indices.recovery.compress`>> установлено в `false`)
|>= 1.3.2       |1.x            |<<rolling-upgrades,Накатывающее обновление>>
|1.x            |2.x            |<<restart-upgrade,Полный перезапуск кластера>>
|=======================================================================

TIP: При обновлении, примите во внимание также и наличие плагинов. Большинство плагинов должны быть обновлены при обновлении Elasticsearch, хотя некоторые из них, в основном работающие через браузер (`_site` плагины), могут продолжить свою работу, с учётом совместимости изменений API.

include::backup.asciidoc[]

include::rolling_upgrade.asciidoc[]

include::cluster_restart.asciidoc[]
